AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: TFT Legends Match Scraper Lambda

Parameters:
  CreateBucket:
    Description: "Whether to create the S3 bucket"
    Type: String
    Default: "Yes"
    AllowedValues:
      - "Yes"
      - "No"

  CreateTrigger:
    Description: "Whether to create the trigger"
    Type: String
    Default: "Yes"
    AllowedValues:
      - "Yes"
      - "No"

Conditions:
  ShouldCreateBucket: !Equals [ !Ref CreateBucket, "No" ]
  ShouldCreateTrigger: !Equals [ !Ref CreateTrigger, "Yes" ]

Resources:
  TFTLegendsMatchScraperLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/main.handler
      Runtime: nodejs18.x
      Description: Fetches TFT matches from Riot API.
      MemorySize: 256
      Timeout: 200
      CodeUri: ./dist
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
                - sqs:ReceiveMessage
              Resource:
                - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/COMMON*'
                - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/TFTLEGENDS_MATCH_SCRAPER*'
                - !Sub 'arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:tft-legends-username-processing-queue'

  TFTLegendsMatchScraperBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Condition: ShouldCreateBucket
    Properties:
      BucketName: tft-legends-match-scraper-package


  TFTLegendsMatchScraperTrigger:
    Type: AWS::Events::Rule
    Condition: ShouldCreateTrigger
    DeletionPolicy: Delete
    Properties:
      Description: Trigger for TFT Legends Match Scraper
      ScheduleExpression: rate(30 minutes)
      State: ENABLED
      Targets:
        - Arn: !GetAtt TFTLegendsMatchScraperLambda.Arn
          Id: TFTLegendsMatchScraperLambda


  TFTLegendsMatchScraperInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt TFTLegendsMatchScraperLambda.Arn
      Principal: 'events.amazonaws.com'
      SourceArn: !GetAtt TFTLegendsMatchScraperLambda.Arn


  TFTLegendsUsernameProcessorQueueEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    DependsOn: TFTLegendsMatchScraperLambda
    Properties:
      BatchSize: 1
      Enabled: true
      EventSourceArn: !Sub 'arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:tft-legends-username-processing-queue'
      FunctionName: !GetAtt TFTLegendsMatchScraperLambda.Arn



  TFTLegendsUsernameProcessorQueuePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt TFTLegendsMatchScraperLambda.Arn
      Principal: 'sqs.amazonaws.com'
      SourceArn: !Sub 'arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:tft-legends-username-processing-queue'
