AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: TFT Legends Match Scraper Lambda

Parameters:
  MetricsNamespace:
    Type: String
    Description: The namespace for the metrics
    Default: 'TFTLegendsMatchScraper'

Resources:
  TFTLegendsMatchScraperLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/main.handler
      Runtime: nodejs18.x
      Description: Fetches TFT matches from Riot API.
      MemorySize: 256
      Timeout: 200
      CodeUri: ./dist
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
                - sqs:ChangeMessageVisibility
              Resource:
                - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/COMMON*'
                - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/TFTLEGENDS_MATCH_SCRAPER*'
                - !Sub 'arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:tft-legends-username-processing-queue'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cloudwatch:PutMetricData
                - cloudwatch:GetMetricStatistics
                - cloudwatch:ListMetrics
              Resource: '*'

  TFTLegendsMatchScraperTrigger:
    Type: AWS::Events::Rule
    DeletionPolicy: Delete
    Properties:
      Description: Trigger for TFT Legends Match Scraper
      ScheduleExpression: rate(15 minutes)
      State: ENABLED
      Targets:
        - Arn: !GetAtt TFTLegendsMatchScraperLambda.Arn
          Id: TFTLegendsMatchScraperLambda


  TFTLegendsMatchScraperInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt TFTLegendsMatchScraperLambda.Arn
      Principal: 'events.amazonaws.com'
      SourceArn:  !GetAtt TFTLegendsMatchScraperTrigger.Arn


  TFTLegendsUsernameProcessorQueueEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    DependsOn: TFTLegendsMatchScraperLambda
    Properties:
      BatchSize: 1
      Enabled: true
      EventSourceArn: !Sub 'arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:tft-legends-username-processing-queue'
      FunctionName: !GetAtt TFTLegendsMatchScraperLambda.Arn



  TFTLegendsUsernameProcessorQueuePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt TFTLegendsMatchScraperLambda.Arn
      Principal: 'sqs.amazonaws.com'
      SourceArn: !Sub 'arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:tft-legends-username-processing-queue'

