export default {
  "Set9_Ionia": "Ionia",
  "Set9_Targon": "Targon",
  "Set9_Zaun": "Zaun",
  "Set9_Freljord": "Freljord",
  "Set9_ShadowIsles": "Shadow Isles",
  "Set9_Noxus": "Noxus",
  "Set9_Piltover": "Piltover",
  "Set9_Demacia": "Demacia",
  "Set9_Shurima": "Shurima",
  "Set9_Void": "Void",
  "Set9_BandleCity": "Bandle City",
  "Set9_Marksman": "Marksman",
  "Set9_Armorclad": "Armorclad",
  "Set9_Challenger": "Challenger",
  "Set9_Deadeye": "Deadeye",
  "Set9_Bruiser": "Bruiser",
  "Set9_Strategist": "Strategist",
  "Set9_Technogenius": "Technogenius",
  "Set9_Multicaster": "Multicaster",
  "Set9_Preserver": "Preserver",
  "Set9_Bastion": "Bastion",
  "Set9_Rogue": "Rogue",
  "Set9_Slayer": "Slayer",
  "Set9_Sorcerer": "Sorcerer",
  "Set9_Redeemer": "Redeemer",
  "Set9_Empress": "Empress",
  "Set9_Wanderer": "Wanderer",
  "Set9b_Darkin": "Darkin",
  "Set9_Ixtal": "Ixtal",
  "Set9b_Bilgewater": "Bilgewater",
  "Set9b_Vanquisher": "Vanquisher",
  "Set9_ReaverKing": "Reaver King"
};
