AWSTemplateFormatVersion: 2010-09-09
Description: Bot Message Processing SQS Queue


Resources:

  BotMessageProcessingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: bot-message-processing-queue
      VisibilityTimeout: 300
      MessageRetentionPeriod: 1209600
      DelaySeconds: 0
      ReceiveMessageWaitTimeSeconds: 0

Outputs:
  MemeQueueUrl:
    Description: The URL of the tft legends username processing SQS queue
    Value:
      Ref: BotMessageProcessingQueue

  MemeQueueArn:
    Description: The ARN of the tft legends username processing SQS queue
    Value: !GetAtt BotMessageProcessingQueue.Arn
