export default {
  "TFT6_Augment_SalvageBin": "Salvage Bin",
  "TFT6_Augment_SlowAndSteady": "March of Progress",
  "TFT6_Augment_PortableForge": "Portable Forge",
  "TFT6_Augment_BinaryAirdrop": "Binary Airdrop",
  "TFT6_Augment_Recombobulator": "Recombobulator",
  "TFT9_Augment_JeweledLotus": "Jeweled Lotus II",
  "TFT6_Augment_Twins2": "Double Trouble II",
  "TFT6_Augment_Twins3": "Double Trouble III",
  "TFT7_Augment_SacrificialPact": "Cruel Pact",
  "TFT7_Augment_PandorasBench": "Pandora's Bench",
  "TFT6_Augment_ThreesCompany": "Three's Company",
  "TFT7_Augment_LivingForge": "Living Forge",
  "TFT7_Augment_AFK": "AFK",
  "TFT7_Augment_LastStand": "Last Stand",
  "TFT6_Augment_RichGetRicher": "Rich Get Richer",
  "TFT6_Augment_RichGetRicherPlus": "Rich Get Richer+",
  "TFT7_Augment_LuckyGloves": "Lucky Gloves",
  "TFT7_Augment_BirthdayPresents": "Birthday Present",
  "TFT7_Augment_TomeOfTraits2": "Ancient Archives II",
  "TFT6_Augment_Traitless2": "Built Different II",
  "TFT6_Augment_Traitless3": "Built Different III",
  "TFT6_Augment_GachaAddict": "Golden Ticket",
  "TFT9_Augment_SilverTicket": "Silver Ticket",
  "TFT9_Augment_YoungAndWildAndFree": "Young and Wild and Free",
  "TFT9_Augment_CyberneticBulk2": "Cybernetic Bulk II",
  "TFT9_Augment_PhreakyFriday": "Phreaky Friday",
  "TFT9_Augment_CyberneticBulk1": "Cybernetic Bulk I",
  "TFT9_Augment_CapriciousForge": "Capricious Forge",
  "TFT9_Augment_CyberneticBulk3": "Cybernetic Bulk III",
  "TFT9_Augment_StarterKit": "Starter Kit",
  "TFT9_Augment_CyberneticLeech1": "Cybernetic Leech I",
  "TFT9_Augment_CyberneticLeech2": "Cybernetic Leech II",
  "TFT9_Augment_LongTimeCrafting": "Latent Forge",
  "TFT9_Augment_CyberneticLeech3": "Cybernetic Leech III",
  "TFT9_Augment_Formation2": "Unified Resistance II",
  "TFT9_Augment_TonsOfStats": "Tons of Stats!",
  "TFT9_Augment_Formation1": "Unified Resistance I",
  "TFT9_Augment_SilverSpoon": "Silver Spoon",
  "TFT9_Augment_TacticiansTools": "Tactician's Tools",
  "TFT9_Augment_CustomerIsAlwaysRight": "Component Buffet",
  "TFT9_Augment_Inconsistency": "Inconsistency",
  "TFT9_Augment_IronAssets": "Iron Assets",
  "TFT9_Augment_OnARoll": "On a Roll",
  "TFT9_Augment_StarsAreBorn": "Stars are Born",
  "TFT9_Augment_ImpromptuInventions": "Scrappy Inventions",
  "TFT9_Augment_KnowledgeIsPower": "Library Card",
  "TFT9_Augment_SocialDistancing": "Social Distancing I",
  "TFT9_Augment_SocialDistancing2": "Social Distancing II",
  "TFT9_Augment_SocialDistancing3": "Social Distancing III",
  "TFT9_Augment_OneTwosThree": "One Twos Three",
  "TFT9_Augment_EnduranceTraining": "Endurance Training",
  "TFT9_Augment_EarlyEducation": "Early Education",
  "TFT9_Augment_IndomitableWill": "Indomitable Will",
  "TFT9_Augment_FinalReserves": "Final Reserves",
  "TFT9_Augment_Shoplifting": "Shoplifting",
  "TFT9_Augment_MissedConnections": "Missed Connections",
  "TFT9_Augment_Infusion": "Infusion",
  "TFT9_Augment_RollTheDice": "Roll The Dice",
  "TFT9_Augment_WhatTheForge": "What The Forge",
  "TFT9_Augment_Sleightofhand": "Sleight of Hand",
  "TFT9_Augment_BloodMoney": "Blood Money",
  "TFT9_Augment_ACutAbove": "A Cut Above",
  "TFT9_Augment_Idealism": "Idealism",
  "TFT9_Augment_HealingOrbsI": "Healing Orbs I",
  "TFT9_Augment_HealingOrbsII": "Healing Orbs II",
  "TFT9_Augment_GargantuanResolve": "Gargantuan Resolve",
  "TFT9_Augment_GiftsFromTheFallen": "Gifts from the Fallen",
  "TFT9_Augment_HedgeFund": "Hedge Fund",
  "TFT9_Augment_HedgeFundPlus": "Hedge Fund+",
  "TFT9_Augment_Martyr": "Martyr",
  "TFT9_Augment_DemaciaEmblem": "Demacia Crest",
  "TFT9_Augment_LongDistanceRelationship2": "Long Distance Pals II",
  "TFT9_Augment_DemaciaEmblem2": "Demacia Crown",
  "TFT9_Augment_FreljordTrait2": "Freljord Soul",
  "TFT9_Augment_FreljordTrait": "Freljord Heart",
  "TFT9_Augment_IoniaEmblem": "Ionia Crest",
  "TFT9_Augment_IoniaEmblem2": "Ionia Crown",
  "TFT9_Augment_NoxusEmblem": "Noxus Crest",
  "TFT9_Augment_NoxusEmblem2": "Noxus Crown",
  "TFT9_Augment_PiltoverTrait2": "Piltover Soul",
  "TFT9_Augment_PiltoverTrait": "Piltover Heart",
  "TFT9_Augment_ShurimaEmblem": "Shurima Crest",
  "TFT9_Augment_ShurimaEmblem2": "Shurima Crown",
  "TFT9_Augment_TargonTrait2": "Targon Soul",
  "TFT9_Augment_TargonTrait": "Targon Heart",
  "TFT9_Augment_VoidEmblem2": "Void Crown",
  "TFT9_Augment_VoidEmblem": "Void Crest",
  "TFT9_Augment_ZaunEmblem": "Zaun Crest",
  "TFT9_Augment_ZaunEmblem2": "Zaun Crown",
  "TFT9_Augment_ZaunTrait": "Zaun Heart",
  "TFT9_Augment_ArmorcladEmblem": "Juggernaut Crest",
  "TFT9_Augment_ArmorcladEmblem2": "Juggernaut Crown",
  "TFT9_Augment_ArmorcladTrait": "Juggernaut Heart",
  "TFT9_Augment_BastionEmblem": "Bastion Crest",
  "TFT9_Augment_BastionEmblem2": "Bastion Crown",
  "TFT9_Augment_BastionTrait": "Bastion Heart",
  "TFT9_Augment_BruiserEmblem": "Bruiser Crest",
  "TFT9_Augment_BruiserEmblem2": "Bruiser Crown",
  "TFT9_Augment_BruiserTrait": "Bruiser Heart",
  "TFT9_Augment_ChallengerEmblem": "Challenger Crest",
  "TFT9_Augment_ChallengerEmblem2": "Challenger Crown",
  "TFT9_Augment_ChallengerTrait": "Challenger Heart",
  "TFT9_Augment_MulticasterTrait2": "Multicaster Soul",
  "TFT9_Augment_PreserverEmblem": "Invoker Crest",
  "TFT9_Augment_PreserverEmblem2": "Invoker Crown",
  "TFT9_Augment_PreserverTrait": "Invoker Heart",
  "TFT9_Augment_RogueEmblem": "Rogue Crest",
  "TFT9_Augment_RogueEmblem2": "Rogue Crown",
  "TFT9_Augment_RogueTrait": "Rogue Heart",
  "TFT9_Augment_SlayerEmblem": "Slayer Crest",
  "TFT9_Augment_SlayerEmblem2": "Slayer Crown",
  "TFT9_Augment_SlayerTrait": "Slayer Heart",
  "TFT9_Augment_SorcererEmblem": "Sorcerer Crest",
  "TFT9_Augment_SorcererEmblem2": "Sorcerer Crown",
  "TFT9_Augment_SorcererTrait": "Sorcerer Heart",
  "TFT9_Augment_StrategistTrait2": "Strategist Soul",
  "TFT9_Augment_StrategistTrait": "Strategist Heart",
  "TFT9_Augment_MarksmanEmblem": "Gunner Crest",
  "TFT9_Augment_MarksmanEmblem2": "Gunner Crown",
  "TFT9_Augment_MarksmanTrait": "Gunner Heart",
  "TFT9_Augment_Contagion": "Contagion",
  "TFT9_Augment_GreaterJeweledLotus": "Jeweled Lotus III",
  "TFT9_Augment_LesserJeweledLotus": "Jeweled Lotus I",
  "TFT9_Augment_BronzeTicket": "Bronze Ticket",
  "TFT9_Augment_BuildingACollection": "Buried Treasures I",
  "TFT9_Augment_BuildingACollectionPlus": "Buried Treasures II",
  "TFT9_Augment_BuildingACollectionPlusPlus": "Buried Treasures III",
  "TFT9_Augment_BranchingOut": "Branching Out",
  "TFT9_Augment_KnowYourEnemy": "Know Your Enemy",
  "TFT9_Augment_Commander_SmallForge": "Small Forge",
  "TFT9_Augment_Commander_MediumForge": "Medium Forge",
  "TFT9_Augment_Commander_LargeForge": "Large Forge",
  "TFT9_Augment_Commander_SmallForgePlus": "Job's Done",
  "TFT9_Augment_Commander_MediumForgePlus": "Job Well Done",
  "TFT9_Augment_Commander_LargeForgePlus": "Masterful Job",
  "TFT6_Augment_TinyTitans": "Tiny Titans",
  "TFT6_Augment_MetabolicAccelerator": "Metabolic Accelerator",
  "TFT9_Augment_Harmacist1": "Harmacist I",
  "TFT9_Augment_Harmacist2": "Harmacist II",
  "TFT9_Augment_Harmacist3": "Harmacist III",
  "TFT6_Augment_PandorasItems": "Pandora's Items",
  "TFT9_Augment_Commander_Experience1Plus": "Knowledge Download 1+",
  "TFT9_Augment_Commander_Experience2Plus": "Knowledge Download II+",
  "TFT9_Augment_Commander_Experience3Plus": "Knowledge Download III+",
  "TFT9_Augment_Commander_Experience1": "Knowledge Download I",
  "TFT9_Augment_Commander_Experience2": "Knowledge Download II",
  "TFT9_Augment_Commander_Experience3": "Knowledge Download III",
  "TFT9_Augment_PandorasRadiantBox": "Pandora's Items III",
  "TFT9_Augment_PandorasItems2": "Pandora's Items II",
  "TFT9_Augment_WhatDoesntKillYou": "What Doesn't Kill You",
  "TFT9_Augment_ArmyBuilding": "Army Building",
  "TFT9_Augment_RiskyMoves": "Risky Moves",
  "TFT6_Augment_HyperRoll": "Hustler",
  "TFT9_Augment_NotToday": "Not Today",
  "TFT6_Augment_OneTwoFive": "One, Two, Five!",
  "TFT9_Augment_DemaciaPetriciteShackles": "Petricite Shackles",
  "TFT9_Augment_ReturnOnInvestment": "Return on Investment",
  "TFT9_Augment_JustKeepRolling": "Frequent Flier",
  "TFT9_Augment_BalancedBudget": "Balanced Budget",
  "TFT9_Augment_Transfusion": "Transfusion I",
  "TFT9_Augment_BalancedBudget2": "Balanced Budget II",
  "TFT9_Augment_TransfusionPlus": "Transfusion II",
  "TFT9_Augment_BalancedBudget3": "Balanced Budget III",
  "TFT9_Augment_TransfusionPlusPlus": "Transfusion III",
  "TFT9_Augment_DravenSpoilsOfWar": "Spoils of War I",
  "TFT9_Augment_DravenSpoilsOfWar2": "Spoils of War II",
  "TFT9_Augment_DravenSpoilsOfWar3": "Spoils of War III",
  "TFT9_Augment_Commander_Money": "Money!",
  "TFT9_Augment_Commander_Money2": "Money Money!",
  "TFT9_Augment_Commander_Money3": "Money Money Money!",
  "TFT9_Augment_PumpingUp": "Pumping Up I",
  "TFT9_Augment_PumpingUp2": "Pumping Up II",
  "TFT9_Augment_PumpingUp3": "Pumping Up III",
  "TFT9_Augment_BattleReady": "Battle Ready",
  "TFT9_Augment_BattleReadyII": "Battle Ready II",
  "TFT9_Augment_BattleReadyIII": "Battle Ready III",
  "TFT9_Augment_TiniestTitan": "Tiniest Titan",
  "TFT9_Augment_GottaGoFast": "Gotta Go Fast!",
  "TFT9_Augment_GottaGoFastII": "Gotta Go Fast! II",
  "TFT9_Augment_GottaGoFastIII": "Gotta Go Fast!!! III",
  "TFT9_Augment_Commander_TinyPower1": "Tiny Power I",
  "TFT9_Augment_FinalGrabBag": "Final Grab Bag",
  "TFT9_Augment_Commander_TinyPower2": "Tiny Power II",
  "TFT9_Augment_Commander_TinyPower3": "Tiny Power III",
  "TFT9_Augment_Commander_PartialAscension": "Partial Ascension",
  "TFT9_Augment_Commander_Ascension": "Ascension",
  "TFT9_Augment_Commander_FinalAscension": "Final Ascension",
  "TFT9_Augment_FinalGrabBagPlus": "Final Grab Bag II",
  "TFT9_Augment_FinalGrabBagPlusPlus": "Urf's Grab Bag",
  "TFT9_Augment_Commander_TeamingUp1": "Teaming Up I",
  "TFT9_Augment_ItemGrabBagPlus": "Item Grab Bag II",
  "TFT9_Augment_Commander_TeamingUp2": "Teaming Up II",
  "TFT9_Augment_Commander_TeamingUp3": "Teaming Up III",
  "TFT9_Augment_Commander_RollingForDays": "Rolling For Days I",
  "TFT9_Augment_Commander_RollingForDays2": "Rolling For Days II",
  "TFT9_Augment_Commander_RollingForDays3": "Rolling For Days III",
  "TFT9_Augment_ItemGrabBagPlusPlus": "Item Grab Bag III",
  "TFT9_Augment_TinyGrabBag": "Tiny Grab Bag",
  "TFT9_Augment_BigGrabBag": "Big Grab Bag",
  "TFT9_Augment_Commander_WellEarnedComforts": "Well-Earned Comforts I",
  "TFT9_Augment_GiantGrabBag": "Giant Grab Bag",
  "TFT9_Augment_Commander_WellEarnedComforts2": "Well-Earned Comforts II",
  "TFT9_Augment_Commander_WellEarnedComforts3": "Well-Earned Comforts III",
  "TFT9_Augment_TopDeck": "Training Reward",
  "TFT9_Augment_TopDeckPlus": "Training Reward II",
  "TFT9_Augment_TopDeckPlusPlus": "Training Reward III",
  "TFT6_Augment_TradeSector": "Trade Sector",
  "TFT9_Augment_ItPaysToLearn": "It Pays To Learn",
  "TFT9_Augment_ItPaysToLearnII": "It Pays to Learn II",
  "TFT9_Augment_ItPaysToLearnIII": "It Pays to Learn III",
  "TFT6_Augment_MaxLevel10": "Level Up!",
  "TFT9_Augment_DangerousToGoAlone": "Parting Gifts",
  "TFT9_Augment_GunnerSpiritOfTheDuelist": "Dueling Gunners",
  "TFT9_Augment_YouHaveMySword": "You Have My Sword",
  "TFT9_Augment_YouHaveMyBow": "You Have My Bow",
  "TFT9_Augment_OldMansWalkingStick": "Magic Wand",
  "TFT9_Augment_EscortQuest": "Escort Quest",
  "TFT9_Augment_ThreesACrowd": "Three's a Crowd",
  "TFT9_Augment_TwoHealthy": "Two Healthy",
  "TFT9_Augment_SettTheBoss": "The Boss",
  "TFT9_Augment_WanderingTrainer": "Wandering Trainer",
  "TFT9_Augment_RedBuff": "Red Buff",
  "TFT9_Augment_TargonStaffOfFlowingWaters": "Stellacorn's Blessing",
  "TFT9_Augment_StrategistTacticalSuperiority": "Tactical Superiority",
  "TFT9_Augment_SorcererOverchargedManafont": "Overcharged Manafont",
  "TFT9_Augment_AllNatural": "All Natural I",
  "TFT9_Augment_AllNatural2": "All Natural II",
  "TFT9_Augment_MoneyHealsAllWounds": "Wellness Trust",
  "TFT9_Augment_LearningFromExperience2": "Patient Study",
  "TFT9_Augment_KassadinCarry": "Riftwalk",
  "TFT6_Augment_RadiantRelics": "Radiant Relics",
  "TFT9_Augment_PiltoverShimmeringInventors": "Shimmering Inventors",
  "TFT9_Augment_GalioCarry": "Winds of War",
  "TFT9_Augment_SlayerSlayersResolve": "Slayer's Resolve",
  "TFT9_Augment_SwainCarry": "Demonflare",
  "TFT9_Augment_RogueVampiricBlades": "Vampiric Blades",
  "TFT9_Augment_InvokerLovingInvocation": "Loving Invocation",
  "TFT9_Augment_MulticasterPracticeMakesPerfect": "Perfected Repetition",
  "TFT9_Augment_ChallengerDefensiveDash": "Defensive Dash",
  "TFT6_Augment_ItemGrabBag1": "Item Grab Bag I",
  "TFT9_Augment_IoniaSentinelsSpirit": "Sentinel's Spirit",
  "TFT9_Augment_JuggernautCantStopMe": "Adrenaline Rush",
  "TFT9_Augment_BastionMorningLight": "Morning Light",
  "TFT9_Augment_VoidRapidIncubation": "Stable Evolution",
  "TFT9_Augment_CombatCaster": "Combat Caster",
  "TFT9_Augment_BruiserTitanicStrength": "Titanic Strength",
  "TFT9_Augment_BlindingSpeed": "Blinding Speed",
  "TFT9_Augment_ImpenetrableBulwark": "Impenetrable Bulwark",
  "TFT9_Augment_UnleashedArcana": "Unleashed Arcana",
  "TFT9_Augment_OverwhelmingForce": "Overwhelming Force",
  "TFT9_Augment_NoxusTotalDomination": "Total Domination",
  "TFT9_Augment_ZaunChemicallyEnhancedBulk": "Chemtech Enhancements",
  "TFT7_Augment_Consistency": "Consistency",
  "TFT7_Augment_LategameSpecialist": "Lategame Specialist",
  "TFT7_Augment_CursedCrown": "Cursed Crown",
  "TFT6_Augment_TheGoldenEgg": "The Golden Egg",
  "TFT9_Augment_HighEndSector": "Shopping Spree",
  "TFT9_Augment_BardPlaybook1": "Caretaker's Ally",
  "TFT9_Augment_BardPlaybook2": "Caretaker's Favor",
  "TFT9_Augment_BardPlaybook3": "Caretaker's Chosen",
  "TFT9_Augment_Legend_LongTimeCrafting": "Latent Forge",
  "TFT6_Augment_Legend_PortableForge": "Portable Forge",
  "TFT7_Augment_Legend_LivingForge": "Living Forge",
  "TFT7_Augment_Legend_AFK": "AFK",
  "TFT6_Augment_Legend_RichGetRicher": "Rich Get Richer",
  "TFT9_Augment_Legend_HedgeFund": "Hedge Fund",
  "TFT9_Augment_Legend_GreaterJeweledLotus": "Jeweled Lotus III",
  "TFT9_Augment_Legend_JeweledLotus": "Jeweled Lotus II",
  "TFT9_Augment_Legend_LesserJeweledLotus": "Jeweled Lotus I",
  "TFT9_Augment_Legend_DravenSpoilsOfWar": "Spoils of War I",
  "TFT9_Augment_Legend_DravenSpoilsOfWar2": "Spoils of War II",
  "TFT9_Augment_Legend_DravenSpoilsOfWar3": "Spoils of War III",
  "TFT6_Augment_Legend_TinyTitans": "Tiny Titans",
  "TFT6_Augment_Legend_MetabolicAccelerator": "Metabolic Accelerator",
  "TFT9_Augment_Legend_TiniestTitan": "Tiniest Titan",
  "TFT9_Augment_Legend_BranchingOut": "Branching Out",
  "TFT6_Augment_Legend_TomeOfTraits1": "Ancient Archives I",
  "TFT7_Augment_Legend_TomeOfTraits2": "Ancient Archives II",
  "TFT9_Augment_Legend_CuttingCorners": "Cutting Corners",
  "TFT9_Augment_Legend_LearningFromExperience2": "Patient Study",
  "TFT6_Augment_Legend_MaxLevel10": "Level Up!",
  "TFT9_Augment_Legend_PumpingUp": "Pumping Up I",
  "TFT9_Augment_Legend_PumpingUp2": "Pumping Up II",
  "TFT9_Augment_Legend_PumpingUp3": "Pumping Up III",
  "TFT9_Augment_Legend_BuildingACollection": "Buried Treasures I",
  "TFT9_Augment_Legend_BuildingACollectionPlus": "Buried Treasures II",
  "TFT9_Augment_Legend_BuildingACollectionPlusPlus": "Buried Treasures III",
  "TFT6_Augment_Legend_TradeSector": "Trade Sector",
  "TFT9_Augment_Legend_HighEndSector": "Shopping Spree",
  "TFT9_Augment_Legend_Transfusion": "Transfusion I",
  "TFT9_Augment_Legend_TransfusionPlus": "Transfusion II",
  "TFT9_Augment_Legend_TransfusionPlusPlus": "Transfusion III",
  "TFT6_Augment_Legend_PandorasItems": "Pandora's Items",
  "TFT9_Augment_Legend_PandorasItems2": "Pandora's Items II",
  "TFT9_Augment_Legend_PandorasRadiantBox": "Pandora's Items III",
  "TFT9_Augment_Legend_BardPlaybook1": "Caretaker's Ally",
  "TFT9_Augment_Legend_BardPlaybook2": "Caretaker's Favor",
  "TFT9_Augment_Legend_BardPlaybook3": "Caretaker's Chosen",
  "TFT9_Augment_Legend_OneTwosThree": "One Twos Three",
  "TFT9_Augment_Legend_StarsAreBorn": "Stars are Born",
  "TFT9_Augment_Legend_StarterKit": "Starter Kit",
  "TFT9_Augment_PhreakyFridayPlus": "Phreaky Friday +",
  "TFT9_Augment_InfernalContract": "Infernal Contract",
  "TFT9_Augment_CuttingCorners": "Cutting Corners",
  "TFT9_Augment_Dedication": "Dedication",
  "TFT9_Augment_HedgeFundPlusPlus": "Hedge Fund++",
  "TFT8_Augment_SalvageBinPlus": "Salvage Bin+",
  "TFT9_Augment_WarwickCarry": "Ravenous Hunter",
  "TFT6_Augment_TomeOfTraits1": "Ancient Archives I",
  "TFT9_Augment_OneHundredDuckSizedHorses": "Endless Hordes",
  "TFT9_Augment_Legend_BronzeTicket": "Bronze Ticket",
  "TFT9_Augment_EnshroudingStillness": "Mana Burn",
  "TFT9_Augment_BilgewaterEmblem": "Bilgewater Crest",
  "TFT6_Augment_PortableForgePlus": "Portable Forge+",
  "TFT9_Augment_BilgewaterEmblem2": "Bilgewater Crown",
  "TFT6_Augment_PortableForgePlusPlus": "Portable Forge++",
  "TFT9_Augment_IxtalTrait": "Ixtal Heart",
  "TFT9_Augment_OneHundredDuckSizedHorsesPlus": "Endless Hordes +",
  "TFT9_Augment_IxtalTrait2": "Ixtal Soul",
  "TFT9_Augment_VanquisherTrait": "Vanquisher Heart",
  "TFT9_Augment_VanquisherEmblem": "Vanquisher Crest",
  "TFT9_Augment_VanquisherEmblem2": "Vanquisher Crown",
  "TFT9_Augment_StationarySupport1": "Stationary Support I",
  "TFT9_Augment_StationarySupport2": "Stationary Support II",
  "TFT9_Augment_StationarySupport3": "Stationary Support III",
  "TFT9_Augment_IxtalRejuvenatingFlames": "Rejuvenating Flames",
  "TFT9_Augment_VanquisherStolenVitality": "Stolen Vitality",
  "TFT9_Augment_BilgewaterRisingInfamy": "Rising Infamy",
  "TFT9_Augment_BilgewaterRisingInfamy2": "Rising Infamy+",
  "TFT9_Augment_BilgewaterRisingInfamy3": "Rising Infamy++",
  "TFT9_Augment_SupportCache": "Support Cache",
  "TFT9_Augment_TiniestTitanPlus": "Tiniest Titan+",
  "TFT7_Augment_LuckyGlovesPlus": "Lucky Gloves"
}
