export default {
  "TFT_Consumable_NeekosHelp": "Champion Duplicator",
  "TFT_Item_BFSword": "B.F. Sword",
  "TFT_Item_Bloodthirster": "Bloodthirster",
  "TFT_Item_BrambleVest": "Bramble Vest",
  "TFT_Item_ChainVest": "Chain Vest",
  "TFT_Item_SparringGloves": "Sparring Gloves",
  "TFT_Item_Deathblade": "Deathblade",
  "TFT_Item_DragonsClaw": "Dragon's Claw",
  "TFT_Item_EmptyBag": "",
  "TFT_Item_ForceOfNature": "Tactician's Crown",
  "TFT_Item_ThiefsGloves": "Thief's Gloves",
  "TFT_Item_ThiefsGloves_Empty": "",
  "TFT_Item_Shroud": "Shroud of Stillness",
  "TFT_Item_FrozenHeart": "Protector's Vow",
  "TFT_Item_GiantsBelt": "Giant's Belt",
  "TFT_Item_MadredsBloodrazor": "Giant Slayer",
  "TFT_Item_GuardianAngel": "Edge of Night",
  "TFT_Item_GuinsoosRageblade": "Guinsoo's Rageblade",
  "TFT_Item_UnstableConcoction": "Hand Of Justice",
  "TFT_Item_HextechGunblade": "Hextech Gunblade",
  "TFT_Item_Chalice": "Chalice of Power",
  "TFT_Item_InfinityEdge": "Infinity Edge",
  "TFT_Item_IonicSpark": "Ionic Spark",
  "TFT_Item_JeweledGauntlet": "Jeweled Gauntlet",
  "TFT_Item_LastWhisper": "Last Whisper",
  "TFT_Item_LocketOfTheIronSolari": "Locket of the Iron Solari",
  "TFT_Item_ArchangelsStaff": "Archangel's Staff",
  "TFT_Item_Spatula": "Spatula",
  "TFT_Item_Quicksilver": "Quicksilver",
  "TFT_Item_Morellonomicon": "Morellonomicon",
  "TFT_Item_NeedlesslyLargeRod": "Needlessly Large Rod",
  "TFT_Item_NegatronCloak": "Negatron Cloak",
  "TFT_Item_PowerGauntlet": "Guardbreaker",
  "TFT_Item_RabadonsDeathcap": "Rabadon's Deathcap",
  "TFT_Item_RapidFireCannon": "Rapid Firecannon",
  "TFT_Item_RecurveBow": "Recurve Bow",
  "TFT_Item_RedBuff": "Sunfire Cape",
  "TFT_Item_Redemption": "Redemption",
  "TFT_Item_RunaansHurricane": "Runaan's Hurricane",
  "TFT_Item_SeraphsEmbrace": "Blue Buff",
  "TFT_Item_SpearOfShojin": "Spear of Shojin",
  "TFT_Item_StatikkShiv": "Statikk Shiv",
  "TFT_Item_GargoyleStoneplate": "Gargoyle Stoneplate",
  "TFT_Item_TearOfTheGoddess": "Tear of the Goddess",
  "TFT_Item_TitanicHydra": "Zz'Rot Portal",
  "TFT_Item_TitansResolve": "Titan's Resolve",
  "TFT_Item_WarmogsArmor": "Warmog's Armor",
  "TFT_Item_ZekesHerald": "Zeke's Herald",
  "TFT_Item_Zephyr": "Zephyr",
  "TFT_Consumable_ItemRemover": "Magnetic Remover",
  "TFT_Consumable_ItemReroller": "Reforger",
  "TFT_Consumable_ShopReroller": "Loaded Dice",
  "TFT_Item_DebugBase": "MissingNo",
  "TFT4_Item_OrnnAnimaVisage": "Anima Visage",
  "TFT4_Item_OrnnDeathsDefiance": "Death's Defiance",
  "TFT4_Item_OrnnEternalWinter": "Eternal Winter",
  "TFT4_Item_OrnnTheCollector": "Gold Collector",
  "TFT4_Item_OrnnInfinityForce": "Infinity Force",
  "TFT4_Item_OrnnMuramana": "Manazane",
  "TFT4_Item_OrnnObsidianCleaver": "Obsidian Cleaver",
  "TFT4_Item_OrnnRanduinsSanctum": "Randuin's Omen",
  "TFT4_Item_OrnnZhonyasParadox": "Zhonya's Paradox",
  "Set5_RadiantItems/TFT5_Item_TrapClawRadiant": "Willbreaker",
  "Set5_RadiantItems/TFT5_Item_BloodthirsterRadiant": "Blessed Bloodthirster",
  "Set5_RadiantItems/TFT5_Item_IonicSparkRadiant": "Covalent Spark",
  "Set5_RadiantItems/TFT5_Item_GiantSlayerRadiant": "Demonslayer",
  "Set5_RadiantItems/TFT5_Item_DragonsClawRadiant": "Dragon's Will",
  "Set5_RadiantItems/TFT5_Item_GargoyleStoneplateRadiant": "Dvarapala Stoneplate",
  "Set5_RadiantItems/TFT5_Item_LastWhisperRadiant": "Eternal Whisper",
  "Set5_RadiantItems/TFT5_Item_HandOfJusticeRadiant": "Fist of Fairness",
  "Set5_RadiantItems/TFT5_Item_FrozenHeartRadiant": "Bulwark's Oath",
  "Set5_RadiantItems/TFT5_Item_JeweledGauntletRadiant": "Glamorous Gauntlet",
  "Set5_RadiantItems/TFT5_Item_GuardianAngelRadiant": "Brink of Dawn",
  "Set5_RadiantItems/TFT5_Item_GuinsoosRagebladeRadiant": "Guinsoo's Reckoning",
  "Set5_RadiantItems/TFT5_Item_HextechGunbladeRadiant": "Hextech Lifeblade",
  "Set5_RadiantItems/TFT5_Item_DeathbladeRadiant": "Luminous Deathblade",
  "Set5_RadiantItems/TFT5_Item_MorellonomiconRadiant": "More More-ellonomicon",
  "Set5_RadiantItems/TFT5_Item_QuicksilverRadiant": "Quickestsilver",
  "Set5_RadiantItems/TFT5_Item_RabadonsDeathcapRadiant": "Rabadon's Ascended Deathcap",
  "Set5_RadiantItems/TFT5_Item_RedemptionRadiant": "Absolution",
  "Set5_RadiantItems/TFT5_Item_RapidFirecannonRadiant": "Rapid Lightcannon",
  "Set5_RadiantItems/TFT5_Item_ThiefsGlovesRadiant": "Rascal's Gloves",
  "Set5_RadiantItems/TFT5_Item_BrambleVestRadiant": "Rosethorn Vest",
  "Set5_RadiantItems/TFT5_Item_RunaansHurricaneRadiant": "Runaan's Tempest",
  "Set5_RadiantItems/TFT5_Item_SpearOfShojinRadiant": "Spear of Hirana",
  "Set5_RadiantItems/TFT5_Item_StatikkShivRadiant": "Statikk's Favor",
  "Set5_RadiantItems/TFT5_Item_SunfireCapeRadiant": "Sunlight Cape",
  "Set5_RadiantItems/TFT5_Item_TitansResolveRadiant": "Titan's Vow",
  "Set5_RadiantItems/TFT5_Item_ArchangelsStaffRadiant": "Urf-Angel's Staff",
  "Set5_RadiantItems/TFT5_Item_WarmogsArmorRadiant": "Warmog's Pride",
  "Set5_RadiantItems/TFT5_Item_InfinityEdgeRadiant": "Zenith Edge",
  "Set5_RadiantItems/TFT5_Item_ZzRotPortalRadiant": "Zz'Rot Portal",
  "TFT_Item_DebugDamage": "Portable Pain",
  "TFT_Item_DebugMana": "The Tears of My Enemies",
  "TFT_Item_DebugStun": "Hammer to the Face",
  "TFT_Item_DebugUnitID": "Do You Know Who I Am?",
  "TFT7_ShimmerscaleItems/TFT7_Item_ShimmerscaleMogulsMail": "Mogul's Mail",
  "TFT7_ShimmerscaleItems/TFT7_Item_ShimmerscaleHeartOfGold": "Needlessly Big Gem",
  "TFT7_ShimmerscaleItems/TFT7_Item_ShimmerscaleGoldmancersStaff": "Goldmancer's Staff",
  "TFT_Consumable_ChampionDuplicator_III": "Lesser Champion Duplicator",
  "TFT9_Item_OrnnHullbreaker": "Hullcrusher",
  "TFT9_Item_OrnnTrickstersGlass": "Trickster's Glass",
  "TFT9_Item_OrnnDeathfireGrasp": "Deathfire Grasp",
  "TFT9_Item_OrnnHorizonFocus": "Sniper's Focus",
  "TFT_Item_UnusableSlot": "Unusable Slot",
  "TFT_Item_BlankSlot": "",
  "TFT_Item_SpectralGauntlet": "Evenshroud",
  "Set5_RadiantItems/TFT5_Item_SpectralGauntletRadiant": "Equinox",
  "TFT_Item_Crownguard": "Crownguard",
  "Set5_RadiantItems/TFT5_Item_CrownguardRadiant": "Royal Crownshield",
  "TFT7_ShimmerscaleItems/TFT7_Item_ShimmerscaleGoldmancersStaff_HR": "Goldmancer's Staff",
  "TFT_Item_NightHarvester": "Night Harvester",
  "TFT7_ShimmerscaleItems/TFT7_Item_ShimmerscaleHeartOfGold_HR": "Needlessly Big Gem",
  "Set5_RadiantItems/TFT5_Item_NightHarvesterRadiant": "Midnight Reaper",
  "TFT7_ShimmerscaleItems/TFT7_Item_ShimmerscaleMogulsMail_HR": "Mogul's Mail",
  "TFT_Item_SteraksGage": "Sterak's Gage",
  "Set5_RadiantItems/TFT5_Item_SteraksGageRadiant": "Sterak's Megashield",
  "TFT_Item_BlueBuff": "Blue Buff",
  "Set5_RadiantItems/TFT5_Item_BlueBuffRadiant": "Blue Blessing",
  "TFT_Item_AdaptiveHelm": "Adaptive Helm",
  "Set5_RadiantItems/TFT5_Item_AdaptiveHelmRadiant": "Jak'sho the Protean",
  "TFT_Item_Leviathan": "Nashor's Tooth",
  "Set5_RadiantItems/TFT5_Item_LeviathanRadiant": "The Baron's Gift",
  "TFT_Item_AegisOfTheLegion": "Aegis of the Legion",
  "TFT_Item_RadiantVirtue": "Virtue of the Martyr",
  "TFT_Item_BansheesVeil": "Banshee's Veil",
  "TFT9_Item_OrnnPrototypeForge": "Blacksmith's Gloves",
  "TFT_Item_DebugShield": "Pengu's Protection",
  "TFT_Item_DebugCrit": "Critical Hit!",
  "TFT9_EmblemItems/TFT9_Item_StrategistEmblem": "Strategist Emblem",
  "TFT9_EmblemItems/TFT9_Item_SlayerEmblem": "Slayer Emblem<br>",
  "TFT9_EmblemItems/TFT9_Item_BrawlerEmblem": "Bruiser Emblem",
  "TFT9_EmblemItems/TFT9_Item_BastionEmblem": "Bastion Emblem",
  "TFT9_EmblemItems/TFT9_Item_ArmorcladEmblem": "Juggernaut Emblem",
  "TFT9_EmblemItems/TFT9_Item_DemaciaEmblem": "Demacia Emblem",
  "TFT9_Items/TFT9_Consumable_GoldenItemRemover": "Golden Item Remover",
  "TFT9_EmblemItems/TFT9_Item_VoidEmblem": "Void Emblem",
  "TFT9_EmblemItems/TFT9_Item_IoniaEmblem": "Ionia Emblem",
  "TFT9_EmblemItems/TFT9_Item_PreserverEmblem": "Invoker Emblem",
  "TFT9_Items/TFT9_Consumable_Chempunk_ChemtankMod": "Hextech Exoskeleton",
  "TFT9_EmblemItems/TFT9_Item_SorcererEmblem": "Sorcerer Emblem",
  "TFT9_Items/TFT9_Consumable_Chempunk_BloodRageMod": "Shimmer Injector",
  "TFT9_Items/TFT9_Consumable_Chempunk_AdaptiveImplantMod": "Adaptive Implant",
  "TFT9_EmblemItems/TFT9_Item_ZaunEmblem": "Zaun Emblem",
  "TFT9_EmblemItems/TFT9_Item_TargonEmblem": "Targon Emblem",
  "TFT9_EmblemItems/TFT9_Item_RogueEmblem": "Rogue Emblem",
  "TFT9_Items/TFT9_Item_WorldEnder_DarkinBlade": "The Darkin Blade",
  "TFT9_EmblemItems/TFT9_Item_TrickshotEmblem": "Gunner Emblem",
  "TFT9_EmblemItems/TFT9_Item_ChallengerEmblem": "Challenger Emblem",
  "TFT9_EmblemItems/TFT9_Item_DeadeyeEmblem": "Deadeye Emblem",
  "DoubleUp_AssistItems/TFT_Assist_Gold_6": "6 gold",
  "DoubleUp_AssistItems/TFT_Assist_Gold_5": "5 gold",
  "DoubleUp_AssistItems/TFT_Assist_Gold_10": "10 gold",
  "TFT8_TheUndergroundItems/TFT_Assist_Gold_20": "20 gold",
  "TFT8_TheUndergroundItems/TFT_Assist_Gold_40": "40 gold",
  "TFT8_TheUndergroundItems/TFT_Assist_Gold_54": "54 gold",
  "TFT9_EmblemItems/TFT9_Item_PiltoverEmblem": "Piltover Emblem",
  "TFT9_EmblemItems/TFT9_Item_NoxusEmblem": "Noxus Emblem",
  "TFT9_EmblemItems/TFT9_Item_ShurimaEmblem": "Shurima Emblem",
  "TFT9_Consumable_EagleEye_Armor": "Eagle's Armor",
  "TFT9_Consumable_EagleEye_MagicResist": "Eagle's Antimagic",
  "TFT9_EmblemItems/TFT9_Item_FreljordEmblem": "Freljord Emblem",
  "TFT9_Items/TFT9_HeimerUpgrade_ShrinkRay": "Shrink Module",
  "TFT9_Items/TFT9_HeimerUpgrade_Goldification": "Goldinator",
  "TFT9_Items/TFT9_HeimerUpgrade_SelfRepair": "Repair-o-matic",
  "TFT9_Items/TFT9_HeimerUpgrade_MicroRockets": "Mechano-Swarm",
  "TFT9_Item_CrownOfDemacia": "Crown of Demacia",
  "TFT9_Items/TFT9_Consumable_MasterworkUpgrade": "Masterwork Upgrade",
  "TFT9_Items/TFT9_Consumable_ScrollOfTraits": "Scroll of Knowledge",
  "TFT9_Items/TFT9_Consumable_Chempunk_UnstableChemtankMod": "Unstable Chemtank",
  "TFT9_Items/TFT9_Consumable_Chempunk_RoboticArmMod": "Robotic Arm",
  "TFT9_Items/TFT9_Consumable_Chempunk_VirulentBiowareMod": "Virulent Bioware",
  "TFT9_EmblemItems/TFT9_Item_ShadowIslesEmblem": "Shadow Isles Emblem",
  "TFT9_Item_PiltoverProgress": "Power",
  "TFT9_Item_PiltoverCharges": "Charges",
  "DoubleUp_AssistItems/TFT_Assist_Gold_7": "7 Gold",
  "DoubleUp_AssistItems/TFT_Assist_Gold_8": "8 gold",
  "TFT7_TreasureDragonDummyItems/TFT7_Item_TreasureDragonGold9": "9 gold",
  "TFT7_TreasureDragonDummyItems/TFT7_Item_TreasureDragonBlankSlot": "",
  "TFT9_Item_CrownOfDemacia_DU": "Crown of Demacia",
  "TFT9_Item_BaronsHead": "Baron Nashor's Head",
  "TFT7_TreasureDragonDummyItems/TFT7_Item_TreasureDragonGold4": "4 Gold",
  "TFT7_TreasureDragonDummyItems/TFT7_Item_TreasureDragonGold3": "3 Gold",
  "TFT7_TreasureDragonDummyItems/TFT7_Item_TreasureDragonGold20": "20 gold",
  "TFT_Consumable_TrainingDummy": "Target Dummy",
  "TFT9_EmblemItems/TFT9_Item_BilgewaterEmblem": "Bilgewater Emblem",
  "TFT9_EmblemItems/TFT9_Item_VanquisherEmblem": "Vanquisher Emblem",
  "TFT9_EmblemItems/TFT9_Item_IxtalEmblem": "Ixtal Emblem",
  "TFT9_Items/TFT9_HeimerUpgrade_RefractorBeam": "Refractor Beam",
  "TFT9_Item_OrnnDuskbladeOfDraktharr": "Duskblade of Draktharr",
};


