export const enum Parameters {
  RIOT_API_KEY = 'TFTLEGENDS_MATCH_SCRAPER_RIOT_API_KEY',
  MATCH_SERVICE_REGION = 'TFTLEGENDS_MATCH_SCRAPER_MATCH_SERVICE_REGION',
  SUMMONER_SERVICE_REGION = 'TFTLEGENDS_MATCH_SCRAPER_SUMMONER_SERVICE_REGION',
  TFT_SET_VERSION = 'TFTLEGENDS_MATCH_SCRAPER_TFT_SET_VERSION',
  TFT_USERNAME = 'TFTLEGENDS_MATCH_SCRAPER_TFT_USERNAME',
  POSTGRES_PORT = 'TFTLEGENDS_MATCH_SCRAPER_POSTGRES_PORT',
  POSTGRES_USER = 'TFTLEGENDS_MATCH_SCRAPER_POSTGRES_USER',
  POSTGRES_PASSWORD = 'TFTLEGENDS_MATCH_SCRAPER_POSTGRES_PASSWORD',
  POSTGRES_DB = 'TFTLEGENDS_MATCH_SCRAPER_POSTGRES_DB',
  POSTGRES_HOST = 'TFTLEGENDS_MATCH_SCRAPER_POSTGRES_HOST',

}
